# Generated by Django 2.1.4 on 2019-02-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_html', '0002_music_kashi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disc',
            name='music10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk10', to='_html.Music', verbose_name='10曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk11', to='_html.Music', verbose_name='11曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk12', to='_html.Music', verbose_name='12曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk13', to='_html.Music', verbose_name='13曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk14', to='_html.Music', verbose_name='14曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk15', to='_html.Music', verbose_name='15曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk16', to='_html.Music', verbose_name='16曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk17', to='_html.Music', verbose_name='17曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk18', to='_html.Music', verbose_name='18曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk19', to='_html.Music', verbose_name='19曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk2', to='_html.Music', verbose_name='2曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk20', to='_html.Music', verbose_name='20曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk21', to='_html.Music', verbose_name='21曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk22', to='_html.Music', verbose_name='22曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk23', to='_html.Music', verbose_name='23曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk24', to='_html.Music', verbose_name='24曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk25', to='_html.Music', verbose_name='25曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk26', to='_html.Music', verbose_name='26曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk27', to='_html.Music', verbose_name='27曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music28',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk28', to='_html.Music', verbose_name='28曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music29',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk29', to='_html.Music', verbose_name='29曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk3', to='_html.Music', verbose_name='3曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music30',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk30', to='_html.Music', verbose_name='30曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music31',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk31', to='_html.Music', verbose_name='31曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music32',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk32', to='_html.Music', verbose_name='32曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music33',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk34', to='_html.Music', verbose_name='33曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music34',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk33', to='_html.Music', verbose_name='34曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music35',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk35', to='_html.Music', verbose_name='35曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk4', to='_html.Music', verbose_name='4曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk5', to='_html.Music', verbose_name='5曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk6', to='_html.Music', verbose_name='6曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk7', to='_html.Music', verbose_name='7曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk8', to='_html.Music', verbose_name='8曲目'),
        ),
        migrations.AlterField(
            model_name='disc',
            name='music9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disk9', to='_html.Music', verbose_name='9曲目'),
        ),
    ]
