# Generated by Django 2.1.4 on 2019-02-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_html', '0003_auto_20190217_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='discript',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='動画の説明（空白可）'),
        ),
        migrations.AlterField(
            model_name='music',
            name='kashi',
            field=models.TextField(blank=True, null=True, verbose_name='歌詞（空白可）'),
        ),
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL(空白可)'),
        ),
        migrations.AlterField(
            model_name='suchedule',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='_html.Image', verbose_name='イベントの画像（空白可）'),
        ),
    ]
